### ISSUE TITLE
ClassicSearch crashing explorer

### ISSUE THREAD

**Issue by Apis035** [krlvm/ClassicSearch#7]
ClassicSearch may randomly crashing the shell everytime an explorer window is opened.

Looking at event viewer logs:
![image](https://github.com/krlvm/ClassicSearch/assets/53115851/b91d6dd6-61cb-48d2-86d3-865687b6f99e)
(In this case, I was editing stuff at Paint.NET and when open/save dialog is opened, both Paint.NET and explorer may randomly crash)

**Comment by krlvm** [comment]
I think it's related to #6, will check what I can do

I did not have any problems with PDN though, do you have Visual C++ Redistributable x64 installed?

**Comment by Apis035** [comment]
Yes I have VC redist installed.

This not happen only on PDN.

![image](https://github.com/krlvm/ClassicSearch/assets/53115851/14560a0d-da90-4605-952a-8c7d6030fdb9)
PowerPoint

![image](https://github.com/krlvm/ClassicSearch/assets/53115851/b863a493-311d-43f4-b455-68df22d821b4)
a live wallpaper app

![image](https://github.com/krlvm/ClassicSearch/assets/53115851/e4851cc5-9f97-4e84-919c-cf9cf12fc948)
Word

![image](https://github.com/krlvm/ClassicSearch/assets/53115851/054de937-1bba-425b-b19e-45e7c140860d)
VSCode

All those happen until I figured out that the culprit was ClassicSearch, so I had to disable it temporarily.

**Comment by krlvm** [comment]
Which version of Windows are you using? I haven't updated for a long time, so I might have missed the moment when it all broke.

**Comment by Apis035** [comment]
Win 10 Pro 22H2 build 19045.3324

**Comment by krlvm** [comment]
Should be fixed in [v1.0.1](https://github.com/krlvm/ClassicSearch/releases/tag/v1.0.1), can you check?

**Comment by Apis035** [comment]
Used the new release. Would need few days to check if this still occurs as it doesn't always happen.

**Comment by Apis035** [comment]
v1.0.1 is still crashing, but now its happens less often than v1.0.0
